[deps]
Archimedes = "d744c896-a888-11e8-2891-21044cb4e99d"
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
CoolProp = "e084ae63-2819-5025-826e-f8e611a84251"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapODEs = "55e38337-5b6e-4c7c-9cfc-e00dd49102e6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
InteractBase = "d3863d7c-f0c8-5437-a7b4-3ae773c01009"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
